### ISSUE TITLE
always OOM on a new/large corpus?

### ISSUE THREAD

**Issue by SeekPoint** [omidai/Predict-next-word#5]
any idea on OOM the shape[32,23997509] , i guess 32 is batch size
but what is the 23997509? how to reduce it

2020-05-11 03:02:14.445838: W tensorflow/core/common_runtime/bfc_allocator.cc:319] ****************************************************************************************____________
2020-05-11 03:02:14.445867: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at assign_op.h:117 : Resource exhausted: OOM when allocating tensor with shape[32,23997509] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn

**Comment by SeekPoint** [comment]
my fault.
I fuck it up.
